service: ${tenant}-set-bot

custom:
  tenant: ${tenant}

provider:
  name: aws
  runtime: nodejs10.x
  apiGateway:
    restApiId:
      Fn::ImportValue: GAIApiGateway-restApiId-${opt:stage}
    restApiRootResourceId:
      Fn::ImportValue: GAIApiGateway-rootResourceId-${opt:stage}
    restApiResources:
      ${tenant}:
        Fn::ImportValue: GAIApiGateway-${tenant}Path

functions:
  setWebhook:
    name: ${tenant}-set-webhook
    description: Function to set the URL for webhook of a telegram bot
    handler: handler.setWebhook
    layers:
      - ${cf:${tenant}-node-layer-${opt:stage}.nodeLayer}
    events:
      - http:
          path: ${tenant}
          method: get
          cors: true
