service: ${tenant}-alphabet-number

provider:
  name: aws
  runtime: python3.7
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sns:Publish
      Resource: "arn:aws:sns:*:*:*"

functions:
  alphabetNumber:
    name: ${tenant}-alphabet-number
    description: Transforma letras em números
    handler: handler.numeros
    layers:
      - ${cf:${tenant}-python-layer-${opt:stage}.pythonLayer}
    events:
      - sns: ${tenant}-alphabet-number
