service: ${tenant}-count-characters

provider:
  name: aws
  runtime: python3.7
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sns:Publish
      Resource: "arn:aws:sns:*:*:*"
    - Effect: Allow
      Action:
        - s3:ListBucket
      Resource: "arn:aws:s3:::*"
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: "arn:aws:s3:::*"
    - Effect: Allow
      Action:
        - s3:GetObjectAcl
      Resource: "arn:aws:s3:::*"
    - Effect: Allow
      Action:
        - s3:PutObjectAcl
      Resource: "arn:aws:s3:::*"

functions:
  countCharacters:
    name: ${tenant}-count-characters
    description: Conta caracteres
    handler: handler.count
    layers:
      - ${cf:${tenant}-python-layer-${opt:stage}.pythonLayer}
    events:
      - sns: ${tenant}-count-characters
