service: ${tenant}-handler-bot

custom:
  tenant: ${tenant}

provider:
  name: aws
  runtime: nodejs10.x
  apiGateway:
    restApiId:
      Fn::ImportValue: GAIApiGateway-restApiId-${opt:stage}
    restApiRootResourceId:
      Fn::ImportValue: GAIApiGateway-rootResourceId-${opt:stage}
    restApiResources:
      ${tenant}:
        Fn::ImportValue: GAIApiGateway-${tenant}Path
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sns:Publish
      Resource: "arn:aws:sns:*:*:*"

functions:
  telegramHandler:
    name: ${tenant}-telegram-handler
    description: Handles the message from telegram
    handler: handler.main
    layers:
      - ${cf:${tenant}-node-layer-${opt:stage}.nodeLayer}
    events:
      - http:
          path: ${tenant}/${telegramTokenId}
          method: post
          cors: true
