service: ${tenant}-number-alphabet

provider:
  name: aws
  runtime: python3.7
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sns:Publish
      Resource: "arn:aws:sns:*:*:*"

functions:
  numberAlphabet:
    name: ${tenant}-number-alphabet
    description: Transforma números em letras
    handler: handler.letras
    layers:
      - ${cf:${tenant}-python-layer-${opt:stage}.pythonLayer}
    events:
      - sns: ${tenant}-number-alphabet
