service: databases

provider:
  name: aws

resources:
  Resources:
    ContextTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Context-${opt:stage}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: chatId
            AttributeType: S
          - AttributeName: command
            AttributeType: S
        KeySchema:
          - AttributeName: chatId
            KeyType: HASH
          - AttributeName: command
            KeyType: RANGE
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Users-${opt:stage}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: cpf
            AttributeType: S
          - AttributeName: birthDate
            AttributeType: S
        KeySchema:
          - AttributeName: cpf
            KeyType: HASH
          - AttributeName: birthDate
            KeyType: RANGE