service: ${tenant}-context-read-bot

provider:
  name: aws
  runtime: nodejs10.x
  environment:
    STAGE: ${opt:stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sns:Publish
        - dynamodb:Query
      Resource: 
        - "arn:aws:sns:*:*:*"
        - "arn:aws:dynamodb:*:*:*"

functions:
  telegramContextRead:
    name: ${tenant}-context-read
    description: Read and send the context of user
    handler: handler.read
    layers:
      - ${cf:${tenant}-node-layer-${opt:stage}.nodeLayer}
    events:
      - sns: ${tenant}-read-telegram-context
