service: ${tenant}-count-characters

provider:
  name: aws
  runtime: python3.7

functions:
  countCharacters:
    name: ${tenant}-count-characters
    description: Conta caracteres
    handler: handler.count
    events:
      - sns: ${tenant}-count-characters
