service: ${tenant}-count-characteres

provider:
  name: aws
  runtime: python3.7
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sns:Publish
      Resource: "arn:aws:sns:*:*:*"

functions:
  countCharacteres:
    name: ${tenant}-count-characteres
    description: Conta caracteres
    handler: handler.count
    layers:
      - ${cf:${tenant}-python-layer-${opt:stage}.pythonLayer}
    events:
      - sns: ${tenant}-count-characteres
