service: ${tenant}-dynamo-write

provider:
  name: aws
  runtime: nodejs10.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sns:Publish
        - dynamodb:PutItem
      Resource: 
        - "arn:aws:sns:*:*:*"
        - "arn:aws:dynamodb:*:*:*"

functions:
  telegramContextWrite:
    name: ${tenant}-dynamo-write
    description: Write something in dynamoDB
    handler: handler.write
    layers:
      - ${cf:${tenant}-node-layer-${opt:stage}.nodeLayer}
    events:
      - sns: ${tenant}-write-dynamo
