service: ${tenant}-get-initials

provider:
  name: aws
  runtime: python3.7
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sns:Publish
      Resource: "arn:aws:sns:*:*:*"

functions:
  getInitials:
    name: ${tenant}-get-initials
    description: Pega as iniciais e finais de uma frase/texto
    handler: handler.iniciais
    layers:
      - ${cf:${tenant}-python-layer-${opt:stage}.pythonLayer}
    events:
      - sns: ${tenant}-get-initials
