service: telegram-api

provider:
  name: aws
  runtime: nodejs10.x

resources:
  Resources:
    GAIApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: GAIApi
    GAIApiPathTelegram:
      Type: AWS::ApiGateway::Resource
      Properties:
        RestApiId: { Ref: "GAIApi" }
        ParentId: { Fn::GetAtt: "GAIApi.RootResourceId" }
        PathPart: telegram
    GAIApiPathGaia:
      Type: AWS::ApiGateway::Resource
      Properties:
        RestApiId: { Ref: "GAIApi" }
        ParentId: { Ref: "GAIApiPathTelegram" }
        PathPart: gaia
    GAIApiPathNathan:
      Type: AWS::ApiGateway::Resource
      Properties:
        RestApiId: { Ref: "GAIApi" }
        ParentId: { Ref: "GAIApiPathTelegram" }
        PathPart: nathan
    GAIApiPathGuilherme:
      Type: AWS::ApiGateway::Resource
      Properties:
        RestApiId: { Ref: "GAIApi" }
        ParentId: { Ref: "GAIApiPathTelegram" }
        PathPart: guilherme

  Outputs:
    apiGatewayRestApiId:
      Value:
        Ref: GAIApi
      Export:
        Name: GAIApiGateway-restApiId-${opt:stage}

    apiGatewayRestApiRootResourceId:
      Value:
        Fn::GetAtt:
          - GAIApi
          - RootResourceId
      Export:
        Name: GAIApiGateway-rootResourceId-${opt:stage}

    apiGatewayRestApiPathGaia:
      Value:
        Ref: GAIApiPathGaia
      Export:
        Name: GAIApiGateway-gaiaPath

    apiGatewayRestApiPathNathan:
      Value:
        Ref: GAIApiPathNathan
      Export:
        Name: GAIApiGateway-nathanPath

    apiGatewayRestApiPathGuilherme:
      Value:
        Ref: GAIApiPathGuilherme
      Export:
        Name: GAIApiGateway-guilhermePath
