service: telegram-api

provider:
  name: aws
  runtime: nodejs10.x

resources:
  Resources:
    GAIApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: GAIApi
    GAIApiPathTelegram:
      Type: AWS::ApiGateway::Resource
      Properties:
        RestApiId: { Ref: "GAIApi" }
        ParentId: { Fn::GetAtt: "GAIApi.RootResourceId" }
        PathPart: telegram

  Outputs:
    apiGatewayRestApiId:
      Value:
        Ref: GAIApi
      Export:
        Name: GAIApiGateway-restApiId-${opt:stage}

    apiGatewayRestApiRootResourceId:
      Value:
        Fn::GetAtt:
          - GAIApi
          - RootResourceId
      Export:
        Name: GAIApiGateway-rootResourceId-${opt:stage}

    apiGatewayRestApiPathTelegram:
      Value:
        Ref: GAIApiPathTelegram
      Export:
        Name: GAIApiGateway-pathTelegram-${opt:stage}